// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTask(arg1:models.TaskInput):Promise<models.TaskOutput>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetTasks(arg1:number):Promise<models.TaskResponse>;

export function UpdateTask(arg1:models.TaskUpdate):Promise<models.TaskSwapBack>;
